name: Build and deploy JAR app to Azure Web App - api-vaga-davinci

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Java version
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'microsoft'

      - name: Build with Maven
        working-directory: 'api-springboot-web-app'  # Corrigido para ser o diretório da aplicação
        run: mvn clean install

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: java-app
          path: '${{ github.workspace }}/api-springboot-web-app/target/*.jar'  # Caminho completo

  deploy:
    runs-on: windows-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write # This is required for requesting the JWT

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: java-app
      
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: "efd57c71-1f19-4870-8600-0dfb46e4165e"  
          tenant-id: "11dbbfe2-89b8-4549-be10-cec364e59551"  
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_4EA08397D2FD435598C1F8FD8014B957 }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'api-vaga-davinci'
          package: '*.jar'  # Caminho completo
          slot-name: 'Production'
